spring:
  context: annotation-config
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: 'app.mzwierzchowski@gmail.com'
    password: 'bxgglpdghxorhsdk'
    port: '587'
api:
  path: api/v1
logging:
  file:
    path: /logs/
    name: logs.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'


